version: 2
jobs:
  build:
    working_directory: /go/src/github.com/robbybt/playground
    docker:
      - image: circleci/golang:1.10
    steps:
      - checkout
      - run:
          name: Downloading dep
          command: echo "gg1"
      - run:
          name: Test os exit 0
          command: go run main.go -test 11
      - run:
          name: Test os exit ga ada
          command: go run main.go -test 6
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
      - run:
          name: Code Has Arrived
          command: |
            ls -al
            echo '^^^That should look familiar^^^'
